version: '3.9'

services:
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
      target: dev
    image: inctnce/time-gen-server-dev
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    container_name: server
    expose:
      - 4000
    ports:
      - 4000:80
    command: npm run dev

  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
      target: dev
    image: inctnce/time-gen-client-dev
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    container_name: client
    expose:
      - 3000
    ports:
      - 3000:80
    command: npm run dev