version: '3.9'

services:
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
      target: dev
    image: inctnce/time-gen-server
    volumes:
      - ./server:/usr/src/app/src
    container_name: server
    expose:
      - 4000
    ports:
      - 4000:80
    command: npm run dev

  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
      target: dev
    image: inctnce/time-gen-client
    volumes:
      - ./client:/usr/src/app/src
    container_name: client
    expose:
      - 3000
    ports:
      - 3000:80
    command: npm run dev
  
  nginx:
    image: nginx:1.17.10
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
        - 80:80
        - 443:443
    depends_on:
        - server
        - client